Repository telekom/scale, pull requests merged in 2021-08, with the labels that each got.

#533 fix(tag): keyboard support for dismiss button
  packages/components/src/components/tag/readme.md
  packages/components/src/components/tag/tag.css
  packages/components/src/components/tag/tag.tsx
  packages/storybook-vue/stories/3_components/tag/ScaleTag.vue
  packages/storybook-vue/stories/3_components/tag/Tag.stories.mdx
Labels: bug

#532 feat: changes for adding list attribute to the scale text field.
  packages/components/src/components/checkbox/readme.md
  packages/components/src/components/data-grid/readme.md
  packages/components/src/components/text-field/readme.md
  packages/components/src/components/text-field/text-field.spec.ts
  packages/components/src/components/text-field/text-field.tsx
Labels: feature

#449 Rating stars refactor + sketch generated stars
  packages/components-sketch/app.js
  packages/components-sketch/package.json
  packages/components-sketch/public/placeCursor.js
  packages/components-sketch/public/symbol_names.js
  packages/components-sketch/views/index.hbs
  packages/components-sketch/views/rating-stars.hbs
  packages/components-sketch/views/rating.hbs
  packages/components-sketch/views/sidebar-nav-components.hbs
  packages/components-sketch/views/sidebar-nav.hbs
  packages/components/scripts/icon-component.hbs
  packages/components/src/components/icon/__snapshots__/icon.spec.ts.snap
  packages/components/src/components/icon/icon.tsx
  packages/components/src/components/rating-stars/__snapshots__/rating-stars.spec.ts.snap
  packages/components/src/components/rating-stars/rating-stars.css
  packages/components/src/components/rating-stars/rating-stars.e2e.ts
  packages/components/src/components/rating-stars/rating-stars.spec.ts
  packages/components/src/components/rating-stars/rating-stars.tsx
  packages/components/src/components/rating-stars/readme.md
  packages/components/src/components/rating-stars/utils/utils.spec.ts
  packages/components/src/components/rating-stars/utils/utils.ts
  packages/components/src/components/telekom/logo/__snapshots__/logo-svg.spec.ts.snap
  packages/components/src/components/telekom/logo/__snapshots__/logo.spec.ts.snap
  packages/components/src/components/telekom/logo/logo-svg.tsx
  packages/components/src/components/telekom/logo/logo.tsx
  packages/components/src/components/telekom/logo/readme.md
  packages/generator-sketch/includes/scale-components-telekom.inc.sketch
  packages/generator-sketch/sketch/symbol_database.sqlite
  packages/generator-sketch/src/config.js
  packages/generator-sketch/src/index.js
  packages/storybook-vue/stories/3_components/logo/Logo.stories.mdx
  packages/storybook-vue/stories/3_components/rating-stars/RatingStars.stories.mdx
  packages/storybook-vue/stories/3_components/rating-stars/ScaleRatingStars.vue
  scripts/build-storybook.sh
  yarn.lock
Labels: accessibility, sketch
