Repository telekom/scale, pull requests merged in 2022-09, with the labels that each got.

#1163 Refactor/tag mobile 📲
  packages/components/src/components/data-grid/cell-handlers/tags-cell.tsx
  packages/components/src/components/tag/__snapshots__/tag.spec.ts.snap
  packages/components/src/components/tag/readme.md
  packages/components/src/components/tag/tag.css
  packages/components/src/components/tag/tag.spec.ts
  packages/components/src/components/tag/tag.tsx
  packages/storybook-vue/stories/components/table/Table.stories.mdx
  packages/storybook-vue/stories/components/tag/ScaleTag.vue
  packages/storybook-vue/stories/components/tag/Tag.stories.mdx
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-a-dissmisable-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-a-small-dismissable-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-a-small-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-dark-color-standard-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-dark-color-strong-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-dark-colors-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-dark-dissmisable-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-dark-small-dismissable-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-dark-small-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-disabled-dismissable-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-light-color-standard-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-light-color-strong-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-light-colors-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-light-dissmisable-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-light-small-dismissable-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-light-small-tag-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-standard-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-variant-secondary-dismissable-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-variant-secondary-dismissable-small-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-variant-secondary-link-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-variant-secondary-small-1-snap.png
  packages/visual-tests/src/__image_snapshots__/tag-visual-spec-js-tag-variant-secondary-tag-1-snap.png
  packages/visual-tests/src/tag.visual.spec.js
Labels: accessibility, preview

#1184 refactor(switch): mobile 📱
  packages/components/src/components/data-grid/readme.md
  packages/components/src/components/switch/__snapshots__/switch.spec.ts.snap
  packages/components/src/components/switch/readme.md
  packages/components/src/components/switch/switch.css
  packages/components/src/components/switch/switch.tsx
  packages/components/src/html/switch.html
  packages/storybook-vue/stories/components/switch/switch.stories.mdx
  packages/visual-tests/src/switch.visual.spec.js
Labels: preview

#1215 refactor: changing dropdown select from 48px height to 44px
  packages/components/src/components/dropdown-select/dropdown-select.css
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-dark-disabled-1-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-dark-disabled-2-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-dark-error-1-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-dark-error-2-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-dark-standard-1-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-dark-standard-2-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-dark-standard-3-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-dark-standard-4-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-light-disabled-1-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-light-disabled-2-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-light-error-1-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-light-error-2-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-light-standard-1-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-light-standard-2-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-light-standard-3-snap.png
  packages/visual-tests/src/__image_snapshots__/dropdown-select-visual-spec-js-dropdown-select-light-standard-4-snap.png
Labels: preview

#1220 feat: secondary white button
  packages/components/src/components/button/button.css
  packages/storybook-vue/stories/components/button/Button.stories.mdx
  packages/visual-tests/src/__image_snapshots__/button-visual-spec-js-button-button-icon-only-2-snap.png
  packages/visual-tests/src/__image_snapshots__/button-visual-spec-js-button-button-icon-only-3-snap.png
  packages/visual-tests/src/__image_snapshots__/button-visual-spec-js-button-button-secondary-2-snap.png
  packages/visual-tests/src/__image_snapshots__/button-visual-spec-js-button-button-secondary-3-snap.png
  packages/visual-tests/src/__image_snapshots__/button-visual-spec-js-button-button-standard-2-snap.png
  packages/visual-tests/src/__image_snapshots__/button-visual-spec-js-button-button-standard-3-snap.png
  packages/visual-tests/src/__image_snapshots__/button-visual-spec-js-button-button-with-icon-before-2-snap.png
  packages/visual-tests/src/__image_snapshots__/button-visual-spec-js-button-button-with-icon-before-3-snap.png
  packages/visual-tests/src/__image_snapshots__/button-visual-spec-js-button-dark-secondary-white-1-snap.png
  packages/visual-tests/src/__image_snapshots__/button-visual-spec-js-button-light-secondary-white-1-snap.png
  packages/visual-tests/src/button.visual.spec.js
Labels: preview

#1221 refactor(slider): mobile 📱
  packages/components/src/components/slider/__snapshots__/slider.spec.ts.snap
  packages/components/src/components/slider/readme.md
  packages/components/src/components/slider/slider.css
  packages/components/src/components/slider/slider.spec.ts
  packages/components/src/components/slider/slider.tsx
  packages/components/src/html/slider.html
  packages/storybook-vue/stories/components/slider/ScaleSlider.vue
  packages/storybook-vue/stories/components/slider/Slider.stories.mdx
Labels: preview

#1222 feat: add helper text and use in text field
  packages/components/src/components/helper-text/__snapshots__/helper-text.spec.ts.snap
  packages/components/src/components/helper-text/__snapshots__/helper-text.spec.tsx.snap
  packages/components/src/components/helper-text/helper-text.css
  packages/components/src/components/helper-text/helper-text.e2e.ts
  packages/components/src/components/helper-text/helper-text.spec.ts
  packages/components/src/components/helper-text/helper-text.tsx
  packages/components/src/components/helper-text/readme.md
Labels: preview

#1175 refactor(callout): a11y 💙
  packages/components/src/components/callout/callout.css
  packages/components/src/components/callout/callout.spec.ts
  packages/components/src/components/callout/callout.tsx
  packages/components/src/components/callout/readme.md
  packages/storybook-vue/stories/components/callout/Callout.stories.mdx
  packages/storybook-vue/stories/components/callout/ScaleCallout.vue
  packages/storybook-vue/stories/components/callout/callout.md
  packages/storybook-vue/stories/components/callout/callout_de.md
  packages/visual-tests/src/callout.visual.spec.js
Labels: accessibility
