Repository telekom/scale, pull requests merged in 2024-08, with the labels that each got.

#2342 ci: sets up docker compose alias for compatibility
  .github/workflows/build-pr.yml
Labels: infrastructure

#2333 dropdown scroll fixed
  packages/components/src/components/dropdown-select/dropdown-select.tsx
Labels: accessibility

#2332 chip accessibility fix
  packages/components/src/components/chip/__snapshots__/chip.spec.ts.snap
  packages/components/src/components/chip/chip.css
  packages/components/src/components/chip/chip.tsx
  packages/components/src/components/chip/readme.md
  packages/components/src/html/chip.html
Labels: accessibility

#2317 checkbox and switch css fixes for high contrast mode
  packages/components/src/components/checkbox/checkbox.css
  packages/components/src/components/switch/switch.css
  packages/components/src/html/checkbox.html
Labels: accessibility

#2341 ghost btn in storybook
  packages/storybook-vue/stories/components/button/Button.stories.mdx
Labels: docs
