Repository telekom/scale, pull requests merged in 2024-10, with the labels that each got.

#2344 data-grid extend localization
  packages/components/src/components/data-grid/cell-handlers/cell-interface.ts
  packages/components/src/components/data-grid/cell-handlers/html-cell.tsx
  packages/components/src/components/data-grid/data-grid.tsx
  packages/components/src/components/data-grid/readme.md
  packages/components/src/html/data-grid.html
  packages/storybook-vue/stories/components/data-grid/DataGrid.stories.mdx
Labels: accessibility

#2339 no userInfo for profile-menu
  packages/components/src/components/telekom/telekom-profile-menu/telekom-profile-menu.css
  packages/components/src/components/telekom/telekom-profile-menu/telekom-profile-menu.tsx
  packages/components/src/html/telekom-header-profile-menu.html
Labels: bug

#2343 tag cell in data-grid extended
  packages/components/src/components/data-grid/cell-handlers/tags-cell.tsx
  packages/components/src/html/data-grid.html
  packages/storybook-vue/stories/components/data-grid/DataGrid.stories.mdx
Labels: feature

#2335 feat(data-grid): adds presort to grid
  packages/components/src/components/data-grid/cell-handlers/cell-interface.ts
  packages/components/src/components/data-grid/data-grid.tsx
  packages/components/src/html/data-grid.html
  packages/storybook-vue/stories/components/data-grid/DataGrid.stories.mdx
Labels: feature

#2358 refactor(segment): improves loading of the component and solves nested elemnts sizing issue
  packages/components/src/components/segment/__snapshots__/segment.spec.ts.snap
  packages/components/src/components/segment/readme.md
  packages/components/src/components/segment/segment.tsx
  packages/components/src/components/segmented-button/__snapshots__/segmented-button.spec.ts.snap
  packages/components/src/components/segmented-button/segmented-button.tsx
  packages/components/src/html/segment-button.html
Labels: bug

#2261 docs: add angular 17 standalone reactive form sample
  examples/angular17-reactive-forms/.editorconfig
  examples/angular17-reactive-forms/.gitignore
  examples/angular17-reactive-forms/README.md
  examples/angular17-reactive-forms/angular.json
  examples/angular17-reactive-forms/package.json
  examples/angular17-reactive-forms/src/app/app.component.css
  examples/angular17-reactive-forms/src/app/app.component.html
  examples/angular17-reactive-forms/src/app/app.component.spec.ts
  examples/angular17-reactive-forms/src/app/app.component.ts
  examples/angular17-reactive-forms/src/app/app.config.ts
  examples/angular17-reactive-forms/src/app/app.routes.ts
  examples/angular17-reactive-forms/src/assets/.gitkeep
  examples/angular17-reactive-forms/src/directives/base-value-accessor.ts
  examples/angular17-reactive-forms/src/directives/checked-value-accessor.ts
  examples/angular17-reactive-forms/src/directives/date-value-accessor.ts
  examples/angular17-reactive-forms/src/directives/number-value-accessor.ts
  examples/angular17-reactive-forms/src/directives/radio-value-accessor.ts
  examples/angular17-reactive-forms/src/directives/select-value-accessor.ts
  examples/angular17-reactive-forms/src/directives/text-value-accessor.ts
  examples/angular17-reactive-forms/src/favicon.ico
  examples/angular17-reactive-forms/src/index.html
  examples/angular17-reactive-forms/src/main.ts
  examples/angular17-reactive-forms/src/styles.css
  examples/angular17-reactive-forms/tsconfig.app.json
  examples/angular17-reactive-forms/tsconfig.json
  examples/angular17-reactive-forms/tsconfig.spec.json
Labels: docs

#2260 fix(nav-item): hover underline on function slots
  packages/components/src/components/telekom/telekom-nav-item/telekom-nav-item.css
Labels: bug

#2357 doc: adds VS code support for Scale customElements
  packages/components/stencil.config.ts
Labels: infrastructure, docs

#2316 fix: pagination with 0 elements
  packages/components/src/components/pagination/pagination.spec.ts
  packages/components/src/components/pagination/pagination.tsx
Labels: bug

#2320 fix(tab-nav): fixes preselect logic in tabs with disabled attribute
  packages/components/src/components/tab-header/readme.md
  packages/components/src/components/tab-header/tab-header.tsx
  packages/components/src/components/tab-nav/tab-nav.tsx
  packages/components/src/html/tab-nav.html
  packages/storybook-vue/stories/components/tab-navigation/ScaleTabNav.vue
  packages/storybook-vue/stories/components/tab-navigation/TabHeader.vue
  packages/storybook-vue/stories/components/tab-navigation/TabNav.stories.mdx
Labels: bug, docs
